name: Node.js CI

on:
  push:
    branches: [ "main", "production" ]
  pull_request:
    branches: [ "main", "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: mock aws-exports
      run: |
          cd src
          cat aws-exports-mock.js > aws-exports.js
          cd ..
    - name: Build next app
      run: DISABLE_ESLINT_PLUGIN=true npm run build
    - name: Save build folder
      uses: actions/upload-artifact@v3
      with:
        name: next-build
        if-no-files-found: error
        path: .next/cache
        retention-days: 1

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: build
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install packages
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          command: cy:ci
        env:
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          CYPRESS_COGNITO_USER_POOL_ID: ${{ secrets.CYPRESS_COGNITO_USER_POOL_ID }}
          CYPRESS_COGNITO_CLIENT_APP_ID: ${{ secrets.CYPRESS_COGNITO_CLIENT_APP_ID }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
